// <auto-generated />
using System;
using EntityFramework.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntityFramework.Model.Bil", b =>
                {
                    b.Property<int>("BilID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BilID"));

                    b.Property<int?>("EjerID")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("BilID");

                    b.HasIndex("EjerID");

                    b.ToTable("Bil");

                    b.HasData(
                        new
                        {
                            BilID = 1,
                            Name = "BMW",
                            Weight = 1400
                        });
                });

            modelBuilder.Entity("EntityFramework.Model.Ejer", b =>
                {
                    b.Property<int>("EjerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EjerID"));

                    b.Property<string>("navn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EjerID");

                    b.ToTable("Ejer");
                });

            modelBuilder.Entity("EntityFramework.Model.Bil", b =>
                {
                    b.HasOne("EntityFramework.Model.Ejer", "Ejer")
                        .WithMany("biler")
                        .HasForeignKey("EjerID");

                    b.Navigation("Ejer");
                });

            modelBuilder.Entity("EntityFramework.Model.Ejer", b =>
                {
                    b.Navigation("biler");
                });
#pragma warning restore 612, 618
        }
    }
}
